### PR TITLE
Alias TCP_KEEPIDLE to TCP_KEEPALIVE for MacOS

### LINKED ISSUE #1: Make fails on MacOS (11.0.1)
Running `make` on MacOS (Intel chip) gives an error:

```
tcp-keepalive-test.c:36:36: error: use of undeclared identifier 'TCP_KEEPIDLE'
    if (setsockopt(s, IPPROTO_TCP, TCP_KEEPIDLE,
                                   ^
```

CC Version info: 
```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
```

### PR DESCRIPTION
**Pull request by olavurdj**
MacOS uses TCP_KEEPALIVE rather than TCP_KEEPIDLE, causing the build to fail. In this small program, a conditional alias may suffice.

Tested and working on MacOS (11.0.1) with Apple clang 12.0.0

fixes #1

### CODE REVIEW

**Comment by AndersTrier** [comment]
Thanks!
